### ISSUE TITLE
Wait load causing plugin issue in tmux

### ISSUE THREAD

**Issue by katernet** [zdharma/zplugin#236]
When I load tmux, my git-prompt plugin is not loading correctly. 

I use my [forked](https://github.com/katernet/git-prompt/blob/master/git-prompt.zsh) version of [woefe/git-prompt.zsh](https://github.com/woefe/git-prompt.zsh)

![tmuxgitprompt1](https://user-images.githubusercontent.com/37143923/71638230-4f04d280-2caa-11ea-9821-32bdd89e4a23.png)

prompt_git:21 can be seen in my dotfiles [repo](https://github.com/katernet/dotfiles/blob/master/.zsh/prompt.zsh#L97)

Here is the code I use to load my forked version

```
zplugin ice wait'' atload'!_zsh_git_prompt_precmd_hook' lucid; zplugin load katernet/git-prompt
```

The recommended zplugin [code](https://github.com/woefe/git-prompt.zsh#zplugin) from woefe is 

```
zplugin ice atload'!_zsh_git_prompt_precmd_hook' lucid
zplugin load woefe/git-prompt.zsh
```

As you can see there is no `wait` and if I remove wait from my code it works fine.

![tmuxgitprompt2](https://user-images.githubusercontent.com/37143923/71638248-026dc700-2cab-11ea-9f93-76371d5d6780.png)

However then I lose turbo mode and my shell load time increases.

I don't think this is an issue with zplugin per se, I think I just need a configuration change somewhere.

How can I use `wait` with this configuration? Any help is appreciated.

**Comment by robobenklein** [comment]
I'm also using an async git-enabled prompt in tmux and recall having a similar issue, but I fixed it so long ago I'm not quite sure what it exactly was.

I load my theme independently: (which should recognize `gitprompt` isn't a command yet and have some kind of fallback/default.
```
zplugin ice nocompletions
zplugin light zinc
```

Then I load a new git provider with turbo: (this would be equivalent to whatever provides your `gitprompt` command)
```
zplugin ice from"gh" wait'1' atload'zinc_optional_depenency_loaded'
```

The zinc_optional_depenency_loaded calls a `.zle reset-prompt` and that prompt redraw then has access to the commands (`gitprompt` in your case) loaded after the turbo is done.

(Actual in-use: https://github.com/robobenklein/configs/blob/master/zsh/zshrc )

If you set the wait to something like 5 seconds you can try to tell when you get those `gitprompt` not found errors. Not likely but it's possible that with wait'0' the first prompt draw is slower than the async loading of the `gitprompt` command.

Most likely it's an out-of-order loading that only appears in tmux because of it's redirection. (i.e. not a real terminal, etc) I also had some problems where the zsh shell in tmux was being started differently (e.x. paths or config locations) than my normal login shell.

**Comment by katernet** [comment]
Great info thanks! Yes git-prompt.zsh uses async. You can turn off async.

So I transferred my theme from sourcing to zplugin (preferred sourcing as no theme refresh on login, but happy to load with zplugin to fix this) and I am now avoiding the errors.

```
zplugin ice wait'' lucid
zplugin light katernet/katernet-zsh-theme

zplugin ice wait'1' atload'!_zsh_git_prompt_precmd_hook' lucid
zplugin light katernet/git-prompt
```

However, I need to press enter in tmux for git-prompt to load.

![Untitled](https://user-images.githubusercontent.com/37143923/71648667-2dadf000-2d57-11ea-8a2c-c278558246f9.png)

wait'1' seems to be fine. Increasing this causes the theme to load slower on shell login.

Investigating

**Comment by psprint** [comment]
Would `wait'!1'` help?

**Comment by katernet** [comment]
Almost there

```
% print $precmd_functions
prompt_precmd _zsh_git_prompt_precmd_hook _zsh_autosuggest_start
```

```
zplugin ice wait'' nocd atload'!prompt_precmd' lucid
zplugin light katernet/katernet-zsh-theme
zplugin ice wait'' atload'!_zsh_git_prompt_precmd_hook' lucid
zplugin light katernet/git-prompt
```
![Untitled](https://user-images.githubusercontent.com/37143923/71649103-be86ca80-2d5b-11ea-8123-6aa14430e642.png)

However, rprompt still not loading before pressing enter.

And weirdly git-prompt is displaying 3 untracked files, when as you can see after pressing enter the local repo is clean.

**Comment by katernet** [comment]
> Would `wait'!1'` help?

```
zplugin ice wait'!1' atload'!_zsh_git_prompt_precmd_hook' lucid
zplugin light katernet/git-prompt
```

![Untitled](https://user-images.githubusercontent.com/37143923/71649355-f0009580-2d5d-11ea-85bd-7639152eb804.png)

```
zplugin ice wait'!0' atload'!_zsh_git_prompt_precmd_hook' lucid
zplugin light katernet/git-prompt
```

![Untitled2](https://user-images.githubusercontent.com/37143923/71649357-f3941c80-2d5d-11ea-80f2-0cc2e13eca5d.png)

**Comment by psprint** [comment]
Maybe passing `nocd` also to the other command would help?

**Comment by katernet** [comment]
That's it! Repo is showing as clean now. Thanks @psprint 

Final code

```
zplugin ice wait'' nocd atload'!prompt_precmd' lucid
zplugin light katernet/katernet-zsh-theme
zplugin ice wait'!' nocd atload'!_zsh_git_prompt_precmd_hook' lucid
zplugin light katernet/git-prompt
```

Also any hints on why the rprompt still doesn't show until I press enter? My theme is located [here](https://github.com/katernet/katernet-zsh-theme/blob/master/katernet-agnoster-theme.zsh)

**Comment by psprint** [comment]
That might be #167, which is an upstream Zsh bug.

**Comment by katernet** [comment]
Interesting. Yes if this is occurring in docker then it is logical that it occurs in tmux. Thanks again.
